name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  package_objects:
    name: Package Objects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy Objects to Output Structure
        run: |
          find "objects" -mindepth 2 -maxdepth 2 -type d | while IFS= read -r category_dir; do
              category="$(basename "$category_dir")"
              dst_dir="./artifacts/objects/$category"

              mkdir -p "$dst_dir"
              find "$category_dir" -type f \( -iname '*.dat' \) | while IFS= read -r dat_file; do
                  filename="$(basename "$dat_file")"
                  cp -f "$dat_file" "$dst_dir/$filename"
              done
          done
      - name: Package Objects
        run: cd artifacts/objects; zip ../../objects.zip ./* -r; cd ../..
      - name: Hash Objects
        run: echo "SHA256=$(sha256sum objects.zip | cut -d " " -f 1)" >> $GITHUB_OUTPUT
        id: hash
      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v4
        with:
          name: objects
          path: objects.zip
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: SHA256:${{ steps.hash.outputs.SHA256 }}
          files: objects.zip
